name: Bug report
description: Report a bug you have encountered
title: "[BUG] "
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Checklist before submitting an issue
      options:
        - label: I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
          required: true
        - label: I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
          required: true
        - label: I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)
          required: true
  - type: textarea
    attributes:
      label: "Description of the bug"
      description: "A clear an concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Reproducing the issue"
      description: "Please provide a clear and and minimal description of how to reproduce the bug. If possible, provide a simple example configuration that shows the issue."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional context"
      description: "If applicable, provide additional context or screenshots here."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Platform and environment"
      description: "Does this happen on wayland, X11, or on both? What WM/Compositor are you using? Which version of eww are you using? (when using a git version, optimally provide the exact commit ref)."
    validations:
      required: true
