#!/bin/sh

if command -v pamixer >/dev/null 2>&1; then
    if [ "$(pamixer --get-mute)" = "true" ]; then
        echo 0
    else
        pamixer --get-volume
    fi
else
    amixer -D pulse sget Master | awk -F'[][]' '/Left:/ { print $2 }' | tr -d '%'
fi
