name: test

on:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        backend-flag: [ "--features=x11",  "--features=wayland", "" ]
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update &&\
          sudo apt-get install libgtk-3-dev libgtk-layer-shell-dev
    - name: Set up
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt
    - name: Add Nextest
      uses: taiki-e/install-action@nextest
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Test
      run: cargo nextest run --no-default-features ${{ matrix.backend-flag }}
